"use client";

import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { daylightAt,formatTime,localClockHours } from "../daylight/daylightModel";
import { ATMOSPHERE_PRESETS,STANDARD_ATMOSPHERE,type AtmosphereProfile } from "../daylight/clearSkyModel";
import { DEFAULT_STORY_MOON,type StoryMoonConfig } from "../daylight/moonlightModel";
import type { GeoLocation } from "../daylight/solarPosition";
import { WebGLRenderer,type ComparisonMode } from "../renderer/WebGLRenderer";

const DEFAULT_IMAGE="/latest-download.png";
const n=(v:number,d=2)=>Number.isFinite(v)?v.toFixed(d):"—";
const localDateValue=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const parseLocalDate=(value:string)=>{const [y,m,d]=value.split("-").map(Number),parsed=new Date(y,m-1,d,12,0,0,0);if(Number.isFinite(parsed.getTime()))return parsed;const fallback=new Date();fallback.setHours(12,0,0,0);return fallback;};
const addLocalDays=(date:Date,days:number)=>{const next=new Date(date);next.setDate(next.getDate()+days);return next;};

function DayCurve({hour,date,location,profile,storyMoon}:{hour:number;date:Date;location:GeoLocation|null;profile:AtmosphereProfile;storyMoon:StoryMoonConfig}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const c=ref.current;if(!c)return;
    const dpr=Math.min(2,devicePixelRatio||1),w=c.clientWidth*dpr,h=c.clientHeight*dpr;c.width=w;c.height=h;
    const x=c.getContext("2d");if(!x)return;x.scale(dpr,dpr);
    const W=c.clientWidth,H=c.clientHeight,samples=288;
    const states=Array.from({length:samples+1},(_,i)=>daylightAt(24*i/samples,date,location,profile,storyMoon).atmosphere);
    const top={y:15,h:60},energy={y:92,h:58},lunar={y:172,h:H-180};
    const line=(color:string,values:(s:(typeof states)[number])=>number,map:(v:number)=>number)=>{x.strokeStyle=color;x.lineWidth=1.3;x.beginPath();states.forEach((s,i)=>{const px=W*i/samples,py=map(values(s));if(i)x.lineTo(px,py);else x.moveTo(px,py);});x.stroke();};
    x.clearRect(0,0,W,H);x.font="7px ui-monospace, monospace";x.fillStyle="#686b6d";
    x.fillText(location?"SUN + MOON ELEVATION · DEG":"STORY SUN + MOON ARC · DEG",7,10);
    x.fillText(location?"CLEAR-SKY IRRADIANCE · W/M²":"QUALITATIVE ENERGY · NORMALIZED",7,87);
    x.fillText(location?"CLEAR-SKY MOONLIGHT · LOG LUX":"STORY MOONLIGHT · LOG ADAPTED LUX",7,167);
    for(const level of [0,-6,-12,-18]){const py=top.y+(72-level)/96*top.h;x.strokeStyle=level===0?"#ffffff26":"#ffffff0d";x.setLineDash(level===0?[]:[2,3]);x.beginPath();x.moveTo(0,py);x.lineTo(W,py);x.stroke();}
    x.setLineDash([]);line("#e8b562",s=>s.geometricElevation,v=>top.y+(72-Math.max(-24,Math.min(72,v)))/96*top.h);
    line("#b8c8de",s=>s.moon.position?.geometricElevation??-24,v=>top.y+(72-Math.max(-24,Math.min(72,v)))/96*top.h);
    for(const plot of [energy,lunar])for(let i=0;i<=2;i++){const py=plot.y+plot.h*i/2;x.strokeStyle="#ffffff0d";x.beginPath();x.moveTo(0,py);x.lineTo(W,py);x.stroke();}
    const energyMap=(v:number)=>energy.y+energy.h*(1-Math.max(0,Math.min(location?1200:1,v))/(location?1200:1));
    line("#d86f4a",s=>location?s.irradiance.dni:s.sunIntensity,energyMap);line("#6f9fd0",s=>location?s.irradiance.dhi:s.skyIrradiance,energyMap);line("#e7ddd0",s=>location?s.irradiance.ghi:Math.max(s.sunIntensity,s.skyIrradiance),energyMap);
    line("#c7d5e8",s=>s.moon.groundIlluminanceLux,v=>lunar.y+lunar.h*(1-Math.max(0,Math.min(1,(Math.log10(Math.max(1e-5,v))+5)/4.5))));
    x.strokeStyle="#f2eee5";x.lineWidth=1;x.beginPath();x.moveTo(W*(hour/24),0);x.lineTo(W*(hour/24),H);x.stroke();
  },[hour,date,location,profile,storyMoon]);
  return <canvas ref={ref} className="day-curve" aria-label="Solar and lunar elevation, clear-sky irradiance, and moonlight plots"/>;
}

export default function DaylightStudio(){
  const canvasRef=useRef<HTMLCanvasElement>(null),viewerRef=useRef<HTMLDivElement>(null),rendererRef=useRef<WebGLRenderer|null>(null),fileRef=useRef<HTMLInputElement>(null),playStartRef=useRef({clock:0,hour:0,date:new Date()});
  const [hour,setHour]=useState(12),[auto,setAuto]=useState(true),[location,setLocation]=useState<GeoLocation|null>(null),[intensity,setIntensity]=useState(1),[split,setSplit]=useState(.5),[comparison,setComparison]=useState<ComparisonMode>("split");
  const [dateValue,setDateValue]=useState(()=>localDateValue());
  const [storyMoon,setStoryMoon]=useState<StoryMoonConfig>({...DEFAULT_STORY_MOON});
  const [profileKind,setProfileKind]=useState<keyof typeof ATMOSPHERE_PRESETS|"Custom">("Standard"),[profile,setProfile]=useState<AtmosphereProfile>({...STANDARD_ATMOSPHERE});
  const [debug,setDebug]=useState(false),[playing,setPlaying]=useState(false),[playSeconds,setPlaySeconds]=useState(30),[imageInfo,setImageInfo]=useState("leste-refugio.png · 1456 × 1080"),[status,setStatus]=useState("Initializing GPU pipeline…");
  const previewDate=useMemo(()=>parseLocalDate(dateValue),[dateValue]);
  const model=useMemo(()=>daylightAt(hour,previewDate,location,profile,storyMoon),[hour,previewDate,location,profile,storyMoon]);const {grade,atmosphere:a}=model;

  useEffect(()=>{if(!canvasRef.current)return;try{const r=new WebGLRenderer(canvasRef.current);rendererRef.current=r;r.setImage(DEFAULT_IMAGE).then(({width,height})=>{setImageInfo(`leste-refugio.png · ${width} × ${height}`);setStatus("");r.setGrade(daylightAt(hour,previewDate,location,profile,storyMoon).grade);}).catch(e=>setStatus(e instanceof Error?e.message:"Image could not be loaded"));return()=>r.destroy();}catch(e){const message=e instanceof Error?e.message:"WebGL initialization failed";queueMicrotask(()=>setStatus(message));}
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);
  useEffect(()=>rendererRef.current?.setGrade(grade),[grade]);
  useEffect(()=>rendererRef.current?.setIntensity(intensity),[intensity]);useEffect(()=>rendererRef.current?.setSplit(split),[split]);useEffect(()=>rendererRef.current?.setComparison(comparison),[comparison]);
  useEffect(()=>{if(!auto||playing)return;const update=()=>{const now=new Date();setHour(localClockHours(now));setDateValue(localDateValue(now));};update();const timer=setInterval(update,1000);return()=>clearInterval(timer);},[auto,playing]);
  useEffect(()=>{if(!playing)return;let frame=0,lastDay=Number.NaN;const tick=(now:number)=>{const elapsedHours=(now-playStartRef.current.clock)/1000*24/playSeconds,total=playStartRef.current.hour+elapsedHours,dayOffset=Math.floor(total/24);setHour(((total%24)+24)%24);if(dayOffset!==lastDay){lastDay=dayOffset;setDateValue(localDateValue(addLocalDays(playStartRef.current.date,dayOffset)));}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,playSeconds]);

  const loadFile=async(file?:File)=>{if(!file||!rendererRef.current)return;setStatus("Loading local image…");try{const {width,height}=await rendererRef.current.setImage(file);setImageInfo(`${file.name} · ${width} × ${height}`);setStatus("");}catch(e){setStatus(e instanceof Error?e.message:"Unsupported image");}};
  const enableSolar=()=>navigator.geolocation?.getCurrentPosition(({coords})=>{setLocation({lat:coords.latitude,lon:coords.longitude});setAuto(true);},()=>setLocation(null),{timeout:7000,maximumAge:3600000});
  const updateStoryMoon=(key:keyof StoryMoonConfig,value:number|boolean)=>setStoryMoon(current=>({...current,[key]:value}));
  const chooseProfile=(value:string)=>{if(value==="Custom"){setProfileKind("Custom");return;}const key=value as keyof typeof ATMOSPHERE_PRESETS;setProfileKind(key);setProfile({...ATMOSPHERE_PRESETS[key]});};
  const updateProfile=(key:keyof Omit<AtmosphereProfile,"name">,value:number)=>{setProfileKind("Custom");setProfile(p=>({...p,name:"Custom",[key]:value}));};
  const updateSplit=useCallback((clientX:number)=>{const r=viewerRef.current?.getBoundingClientRect();if(r)setSplit(Math.max(0,Math.min(1,(clientX-r.left)/r.width)));},[]);
  const startSplitDrag=(e:React.PointerEvent)=>{e.currentTarget.setPointerCapture(e.pointerId);updateSplit(e.clientX);};
  const physicalValue=(value:number)=>location?`${Math.round(value)} W/m²`:n(value,3);
  const metrics:[[string,string],[string,string]][]=[[["Solar elevation",`${n(a.geometricElevation,2)}°`],["Solar azimuth",`${n(a.azimuth,1)}°`]],[["Solar time",formatTime(a.solarTime)],["Optical air mass",a.airMass?n(a.airMass,2):"—"]],[["DNI",physicalValue(location?a.irradiance.dni:a.sunIntensity)],["DHI",physicalValue(location?a.irradiance.dhi:a.skyIrradiance)]],[["GHI",physicalValue(location?a.irradiance.ghi:Math.max(a.sunIntensity,a.skyIrradiance))],["Direct fraction",n(a.directDiffuseRatio,3)]],[["Sun CCT",`${Math.round(a.sunCCT)} K`],["Sky CCT",`${Math.round(a.skyCCT)} K`]],[["Sun chromaticity",`${n(a.sunIlluminant.xy[0],3)}, ${n(a.sunIlluminant.xy[1],3)}`],["Sky chromaticity",`${n(a.skyIlluminant.xy[0],3)}, ${n(a.skyIlluminant.xy[1],3)}`]],[["Rayleigh loss",n(a.rayleigh,3)],["Aerosol loss",n(a.mie,3)]],[["Haze",n(a.haze,3)],["Spectral separation",n(a.spectralSeparation,3)]],[["Low-sun response",n(a.lowSunFactor,3)],["Twilight",n(a.twilight,3)]],[["Night",n(a.night,3)],["Deep-night depth",n(a.deepNightDepth,3)]],[["Dark-arc progress",n(a.nightProgress,3)],["Evening afterglow",n(a.eveningAfterglow,3)]],[["Pre-dawn airglow",n(a.preDawnAirglow,3)],["Visual adaptation",n(a.scotopicAdaptation,3)]]];
  const moon=a.moon,moonPosition=moon.position;
  const moonLux=(value:number)=>value>0?`${value<.001?value.toExponential(2):n(value,4)} lux`:"0 lux";
  const moonMetrics:[[string,string],[string,string]][]=[
    [["Moon elevation",moonPosition?`${n(moonPosition.geometricElevation,2)}°`:"Unavailable"],["Moon azimuth",moonPosition?`${n(moonPosition.azimuth,1)}°`:"Unavailable"]],
    [["Moon phase angle",moonPosition?`${n(moonPosition.phaseAngle,1)}°`:"Unavailable"],["Illuminated",moonPosition?`${n(moonPosition.illuminatedFraction*100,1)}% ${moonPosition.waxing?"waxing":"waning"}`:"Unavailable"]],
    [["Moon distance",moonPosition?`${Math.round(moonPosition.distanceKm).toLocaleString()} km`:"Unavailable"],["Lunar air mass",moon.opticalAirMass?n(moon.opticalAirMass,2):"—"]],
    [["Lunar transmission",moon.available?n(moon.atmosphericTransmission,3):"Unavailable"],["Ground moonlight",moon.available?moonLux(moon.groundIlluminanceLux):"Unavailable"]],
    [["Lunar contribution",moon.available?n(a.moonlightContribution,3):"Unavailable"],["Moon spectrum",moon.available?`${Math.round(moon.spectralIlluminant.cct)} K`:"Unavailable"]],
  ];

  return <main className="studio">
    <header className="topbar"><div className="brand"><i className="brand-mark"/><span>Daylight / Color Studio</span></div><div className="top-actions"><button className="chip source-chip" onClick={()=>fileRef.current?.click()}>Open image</button><button className={`chip ${debug?"active":""}`} onClick={()=>setDebug(v=>!v)}>Physics</button><button className={`chip ${comparison==="original"?"active":""}`} onClick={()=>setComparison(comparison==="original"?"graded":"original")}>{comparison==="original"?"Show grade":"Original"}</button><button className={`chip ${comparison==="split"?"active":""}`} onClick={()=>setComparison(comparison==="split"?"graded":"split")}>Compare</button><input ref={fileRef} className="file-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>loadFile(e.target.files?.[0])}/></div></header>
    <section className="workspace"><div className="viewer" ref={viewerRef}><canvas ref={canvasRef} aria-label="GPU color graded image preview"/>{status&&<div className="loading">{status}</div>}{comparison==="split"&&<><span className="compare-tag before">Original</span><span className="compare-tag after">Graded</span><div className="split-handle" role="slider" aria-label="Before and after split" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(split*100)} tabIndex={0} style={{left:`${split*100}%`}} onPointerDown={startSplitDrag} onPointerMove={e=>e.currentTarget.hasPointerCapture(e.pointerId)&&updateSplit(e.clientX)} onKeyDown={e=>{if(e.key==="ArrowLeft")setSplit(v=>Math.max(0,v-.02));if(e.key==="ArrowRight")setSplit(v=>Math.min(1,v+.02));}}/></>}<span className="image-caption">{imageInfo}</span></div>
      <aside className="panel" aria-label="Daylight grade controls"><div className="panel-section"><div className="eyebrow">{location?"Physical atmosphere":"Fictional atmosphere"}</div><div className="phase-row"><div className="phase-name">{grade.name}</div><div className="timecode">{formatTime(hour)}</div></div><div className="phase-sub">{grade.description}</div></div>
        <div className="panel-section"><div className="control-head"><span>Time of day</span><span className="value">{formatTime(hour)}</span></div><input aria-label="Time of day" type="range" min="0" max="1439" value={Math.round(hour*60)%1440} onInput={e=>{setPlaying(false);setAuto(false);setHour(Number(e.currentTarget.value)/60);}}/><div className="ticks"><span>00</span><span>06</span><span>12</span><span>18</span><span>24</span></div><div className="date-row"><input aria-label="Preview date" type="date" value={dateValue} onChange={e=>{setPlaying(false);setAuto(false);setDateValue(e.target.value);}}/><button className="chip" onClick={()=>{const now=new Date();setPlaying(false);setAuto(false);setDateValue(localDateValue(now));}}>Today</button></div><div className="mode-row"><button className={`chip ${auto?"active":""}`} onClick={()=>{setPlaying(false);setAuto(true);}}>Auto time</button><button className={`chip ${!auto&&!playing?"active":""}`} onClick={()=>{setPlaying(false);setAuto(false);}}>Manual</button></div><div className="play-row"><button className={`chip ${playing?"active":""}`} onClick={()=>{if(playing)setPlaying(false);else{setAuto(false);playStartRef.current={clock:performance.now(),hour,date:previewDate};setPlaying(true);}}}>{playing?"Pause day":"Play full day"}</button><select aria-label="Full-day playback duration" value={playSeconds} onChange={e=>{playStartRef.current={clock:performance.now(),hour,date:previewDate};setPlaySeconds(Number(e.target.value));}}><option value="15">15 sec</option><option value="30">30 sec</option><option value="60">60 sec</option></select></div><div className="hint">{location?`Real-world Sun + Moon · ${n(location.lat,2)}°, ${n(location.lon,2)}°`:"Story Sky · no device location required"}</div></div>
        <div className="panel-section"><div className="control-head"><span>Grade intensity</span><span className="value">{Math.round(intensity*100)}%</span></div><input className="intensity" aria-label="Grade intensity" type="range" min="0" max="100" value={Math.round(intensity*100)} onInput={e=>setIntensity(Number(e.currentTarget.value)/100)}/></div>
        <div className="panel-section story-controls"><div className="control-head"><span>Celestial source</span><span className="value">{location?"REAL SKY":"STORY SKY"}</span></div><div className="mode-row"><button className={`chip ${!location?"active":""}`} onClick={()=>setLocation(null)}>Story sky</button><button className={`chip ${location?"active":""}`} onClick={enableSolar}>Match device</button></div>{!location&&<><div className="control-head story-control-head"><span>Moon illumination</span><span className="value">{Math.round(storyMoon.illuminatedFraction*100)}%</span></div><input aria-label="Story Moon illumination" type="range" min="1" max="100" value={Math.round(storyMoon.illuminatedFraction*100)} onInput={e=>updateStoryMoon("illuminatedFraction",Number(e.currentTarget.value)/100)}/><div className="control-head story-control-head"><span>Moon transit</span><span className="value">{formatTime(storyMoon.transitHour)}</span></div><input aria-label="Story Moon transit time" type="range" min="0" max="1439" value={Math.round(storyMoon.transitHour*60)} onInput={e=>updateStoryMoon("transitHour",Number(e.currentTarget.value)/60)}/></>}<div className="hint">Story Sky creates a continuous fictional Moon arc. Device location is optional and only needed to match Earth’s real sky.</div></div>
        <div className="panel-section atmosphere-controls"><div className="control-head"><span>Atmosphere profile</span><span className="value">{profileKind.toUpperCase()}</span></div><select aria-label="Atmosphere profile" value={profileKind} onChange={e=>chooseProfile(e.target.value)}><option>Clean</option><option>Standard</option><option>Hazy</option><option>Custom</option></select><details><summary>Advanced assumptions</summary><div className="profile-grid"><label>Sea-level hPa<input type="number" min="500" max="1100" step="1" value={profile.pressureHpa} onChange={e=>updateProfile("pressureHpa",Number(e.target.value))}/></label><label>Altitude m<input type="number" min="-500" max="6000" step="10" value={profile.altitudeM} onChange={e=>updateProfile("altitudeM",Number(e.target.value))}/></label><label>Water cm<input type="number" min="0" max="8" step="0.1" value={profile.precipitableWaterCm} onChange={e=>updateProfile("precipitableWaterCm",Number(e.target.value))}/></label><label>Ozone atm-cm<input type="number" min="0.1" max="0.6" step="0.01" value={profile.ozoneAtmCm} onChange={e=>updateProfile("ozoneAtmCm",Number(e.target.value))}/></label><label>AOD 500 nm<input type="number" min="0" max="0.8" step="0.01" value={profile.aerosolOpticalDepth500} onChange={e=>updateProfile("aerosolOpticalDepth500",Number(e.target.value))}/></label><label>Ångström α<input type="number" min="0.2" max="2.5" step="0.1" value={profile.angstromExponent} onChange={e=>updateProfile("angstromExponent",Number(e.target.value))}/></label><label>Ground albedo<input type="number" min="0" max="0.95" step="0.01" value={profile.groundAlbedo} onChange={e=>updateProfile("groundAlbedo",Number(e.target.value))}/></label></div></details><div className="hint">Cloudless offline estimate. These assumptions replace live weather observations.</div></div>
        {debug&&<div className="panel-section physics-panel"><div className="control-head"><span>Atmospheric model</span><span className="value">{location?"CLEAR-SKY PHYSICAL MODEL":"ART-DIRECTED STORY SKY"}</span></div><DayCurve hour={hour} date={previewDate} location={location} profile={profile} storyMoon={storyMoon}/><div className="curve-legend"><span>Sun elevation</span><span>Moon elevation</span><span>DNI</span><span>DHI</span><span>GHI</span><span>Moon lux</span></div><div className={`model-notice ${location?"physical":"reference"}`}>{location?"Cloudless Sun + Moon estimate · W/m² and lux remain separate":"Fictional Moon phase and arc · continuous, deterministic, non-geographic"}</div>{[...metrics,...moonMetrics].map((row,i)=><div className="metric-row" key={i}>{row.map(([label,value])=><div key={label}><div className="stat-label">{label}</div><div className="stat-value">{value}</div></div>)}</div>)}</div>}
        {!debug&&<div className="panel-section"><div className="stat-grid"><div><div className="stat-label">Elevation</div><div className="stat-value">{n(a.elevation,1)}°</div></div><div><div className="stat-label">Air mass</div><div className="stat-value">{n(a.airMass,2)}</div></div><div><div className="stat-label">Exposure</div><div className="stat-value">{grade.exposure>=0?"+":""}{n(grade.exposure)} EV</div></div><div><div className="stat-label">Film density</div><div className="stat-value">{Math.round(grade.filmStrength*100)}%</div></div></div></div>}
      </aside></section><footer className="bottombar"><div className="legend"><span>WebGL2 active</span><span>Continuous solar + lunar model</span><span>32³ film LUT</span></div><div>Celestial geometry → atmosphere → cinematic interpretation</div></footer>
  </main>;
}
